defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "carlos"
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      
