comments: true 

google_analytics: "G-DXWEJDYSTQ"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      path: "blog"
      author: "carlos"
      # layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      
paginate: 5
paginate_path: "/blog/page:num"
